# Generated by Django 4.2.1 on 2023-05-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='games',
            table='ts_games',
        ),
        migrations.AlterModelTable(
            name='leagues',
            table='ts_leagues',
        ),
        migrations.AlterModelTable(
            name='matches',
            table='ts_matches',
        ),
        migrations.AlterModelTable(
            name='playerparticipation',
            table='ts_player_participation',
        ),
        migrations.AlterModelTable(
            name='players',
            table='ts_players',
        ),
        migrations.AlterModelTable(
            name='season',
            table='ts_seasons',
        ),
        migrations.AlterModelTable(
            name='teams',
            table='ts_teams',
        ),
    ]
